config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'search' => 'welcome#search'

  post 'results/multiple_results' => 'results#multiple_results'

  get 'download_sessions' => 'welcome#download_sessions'

  get 'poller_sessions' => 'welcome#poller_sessions'

  get 'poller_session' => 'welcome#poller_session'

  get 'crons' => 'welcome#crons'

  get 'queue' => 'welcome#queue'

  get 'exchange/:exchange' => 'welcome#exchange'

  put 'indicators/update_many' => 'indicators#update_many'

  get 'our_story' => "welcome#our_story"

  resources :results
  resources :visualizations
  resources :stocks
  resources :exchanges
  resources :indicators

  namespace :sitemap do 
    resources :sitemaps
  end

  get 'all_exchanges' => 'exchanges#all', as: "all_exchanges"
  post 'exchange_summary' => 'exchanges#summary', as: "exchange_summary"
  post 'exchange_download_history' => 'exchanges#exchange_download_history', as: 'exchange_download_history'

  
  get 'stocks/:id/with_stock/:primary_stock_id' => "stocks#show", as: "combination_entity"
  get 'stocks/:id/with_indicator/:indicator_id' => "stocks#show", as: "combination_indicator" 
  get 'stocks/:id/:trend_direction' => "stocks#show", as: "direction_entity"
  get 'stocks/:id/with_stock/:primary_stock_id/with_indicator/:indicator_id' => "stocks#show"
  get 'stocks/:id/with_exchange/:exchange_id' => "stocks#show"
  put 'force_create_index' => "stocks#force_create_index", as: "force_create_index"

  get 'stock_ticks' => 'stocks#ticks', as: "stock_ticks"
  get 'stock_download_history' => 'stocks#download_history', as: "stock_download_history"
  get 'stock_errors' => 'stocks#errors', as: "stock_errors"
  get 'stock_poller_history' => 'stocks#poller_history', as: "stock_poller_history"
  post 'update_tick_verified' => 'stocks#update_tick_verified'
   
  

  get '/sitemap.xml.gz', to: redirect("https://storage.googleapis.com/algorini/sitemaps/sitemap.xml.gz", status: 301)

end

app/models/logs/entity.rb
require 'elasticsearch/persistence/model'

class Logs::Entity
	
	include Elasticsearch::Persistence::Model

	attribute :name, String

	attribute :count, Integer

	attribute :information, Array

	index_name "tradegenie_titan"
	document_type "doc"

	STARTED_ENTITY_POLL_PROCESS = "A1s0-ENTITY_STARTED_POLL_PROCESS";
	ENTITY_TASK_STARTED = "A1s-ENTTIY_TASK_STARTED";
	ENTITY_TASK_ERROR = "A1s-ENTTIY_TASK_ERROR";
	TASK_INFO = "A1z1a-TASK_INFO";
	ENTITY_TASK_FINISHED = "A1t-ENTITY_TASK_FINISHED";
	FUTURES_RETRIEVED = "A1t1-FUTURES_RETRIEVED";
	FUTURE_RETRIEVE_ERROR = "A1t2-FUTURE_RETRIEVE_ERROR";
	EXECUTOR_WAITING_TO_SHUTDOWN = "A1t3-EXECUTOR_WAITING_TO_SHUTDOWN";
	EXECUTOR_SHUTDOWN_COMPLETED = "A1t4-EXECUTOR_SHUTDOWN_COMPLETED";
	FRONTEND_UPDATE = "A1u1a-FRONTEND_UPDATE";
	COMPLEX_PAIR = "A1u2-COMPLEX_PAIR";

	FRONTEND_LOG = "frontend_log"
	LOG_INDEX_NAME = "tradegenie_titan"
	LOG_INDEX_TYPE = "doc"
	LOG_INDEX_POLLER_SESSION_TYPE = "Poller"

	START_FRONTEND_UPDATE = "start_frontend_update"
	FRONTEND_UPDATE_AUTH_ERRPR = "frontend_update_auth_error"
	FRONTEND_UPDATE_ERROR = "frontend_update_error"	
	FRONTEND_UPDATE_COMPLETED = "frontend_update_completed"
	START_BACKGROUND_UPDATE = "start_background_update"
	BACKGROUND_UPDATE_ERROR = "background_update_error"
	BACKGROUND_UPDATE_COMPLETED = "background_update_completed"

	FRONTEND_EVENTS = [START_FRONTEND_UPDATE,FRONTEND_UPDATE_AUTH_ERRPR,FRONTEND_UPDATE_ERROR,FRONTEND_UPDATE_COMPLETED,START_BACKGROUND_UPDATE,BACKGROUND_UPDATE_ERROR,BACKGROUND_UPDATE_COMPLETED]


	POLLER_EVENTS = [STARTED_ENTITY_POLL_PROCESS,ENTITY_TASK_STARTED,ENTITY_TASK_ERROR,ENTITY_TASK_FINISHED,FUTURES_RETRIEVED,FUTURE_RETRIEVE_ERROR,EXECUTOR_WAITING_TO_SHUTDOWN,EXECUTOR_SHUTDOWN_COMPLETED,FRONTEND_UPDATE,COMPLEX_PAIR]


	def self.index_properties
		{
			:name => {
				:type => 'keyword'
			},
			:count => {
				:type => 'integer'
			},
			:information => {
				:type => 'keyword'
			}
		}
	end

	###########################################################
	##
	##
	##
	## FRONTEND UPDATE LOGGING DETAILS.
	##
	##
	##
	###########################################################
	def self.frontend_auth_error(args={})
		create_response = Elasticsearch::Persistence.client.create :index => LOG_INDEX_NAME, :type => LOG_INDEX_TYPE, :id => SecureRandom.uuid, :body => {
				:event_name => FRONTEND_UPDATE_AUTH_ERRPR,
				:time => Time.now.to_i*1000
			}
	end

	def self.start_frontend_update(args={})
		create_response = Elasticsearch::Persistence.client.create :index => LOG_INDEX_NAME, :type => LOG_INDEX_TYPE, :id => SecureRandom.uuid, :body => args.merge({
				:event_name => START_FRONTEND_UPDATE,
				:time => Time.now.to_i*1000
			})
	end

	def self.frontend_update_errors(args={})
		create_response = Elasticsearch::Persistence.client.create :index => LOG_INDEX_NAME, :type => LOG_INDEX_TYPE, :id => SecureRandom.uuid, :body => args.merge({:event_name => FRONTEND_UPDATE_ERROR, :time => Time.now.to_i*1000})
	end

	def self.frontend_update_completed(args={})
		create_response = Elasticsearch::Persistence.client.create :index => LOG_INDEX_NAME, :type => LOG_INDEX_TYPE, :id => SecureRandom.uuid, :body => args.merge({:event_name => FRONTEND_UPDATE_COMPLETED, :time => Time.now.to_i*1000})
	end

	def self.start_background_update(args={})
		create_response = Elasticsearch::Persistence.client.create :index => LOG_INDEX_NAME, :type => LOG_INDEX_TYPE, :id => SecureRandom.uuid, :body => args.merge({
				:event_name => START_BACKGROUND_UPDATE,
				:time => Time.now.to_i*1000
			})	
	end

	def self.background_update_errors(args={})
		create_response = Elasticsearch::Persistence.client.create :index => LOG_INDEX_NAME, :type => LOG_INDEX_TYPE, :id => SecureRandom.uuid, :body => args.merge({
				:event_name => BACKGROUND_UPDATE_ERROR,
				:time => Time.now.to_i*1000
			})		
	end

	def self.background_update_completed(args={})
		create_response = Elasticsearch::Persistence.client.create :index => LOG_INDEX_NAME, :type => LOG_INDEX_TYPE, :id => SecureRandom.uuid, :body => args.merge({
				:event_name => BACKGROUND_UPDATE_COMPLETED,
				:time => Time.now.to_i*1000
			})			
	end

=begin
:entity_unique_name => args[:entity].entity_unique_name,
:indice => args[:entity].indice,
:poller_session_id => self.poller_session_id,
:poller_session_type => LOG_INDEX_POLLER_SESSION_TYPE,
:information => "x/y/z",
=end
	

	##########################################################


	def self.entities_query(args)
		#puts "args coming into entities querys are:"
		#puts args.to_s
		
		base = {
			bool: {
				must: []
			}
		}

		if args[:entity_unique_name]
			base[:bool][:must] << {
				term: {
					unique_name: args[:entity_unique_name]
				}
			}
		end

		if args[:exchange_name]
			base[:bool][:must] << {
				term: {
					indice: args[:exchange_name]
				}
			}
		end

		base
	end

	## so we can click to get an entities download history.
	## to get the idea of what has been happening with it.
	## by time.
	## so on clicking on an entity -> we can get its download history.
	## we want query -> where error is there(event_name)
	## and then aggregate those on poller_session_id.
	## sorted descending.
	def self.entities_aggregation(args)
		{
	    	entities: {
	      		terms: {
	        		field: "entity_unique_name",
	        		size: 10,
	        		exclude: ["all_entities"]
	      		},
		      	aggs: {
		      		entity_id: {
		      			terms: {
		      				field: "_id"
		      			}
		      		},
		      		last_10_poller_sessions: {
		      			terms: {
		      				field: "poller_session_id",
		      				order: {
		      					download_session_time: "desc"
		      				}
		      			},
		      			aggs: {
		      				download_events: {
		      					terms: {
		      						field: "event_name",
		      						include: ["A1e-DOWNLOADING_ENTITY","A1i-ENTITY_DOWNLOAD_ERROR","A1h-ENTITY_FORCE_REDOWNLOAD","A1g-ENTITY_EXPECTED_DATAPOINT_ABSENT","A1f-ENTITY_DOWNLOADED_DATE_AND_DATAPOINTS","A1j-ENTITY_NO_NEW_DATAPOINTS"]
		      					}
		      				},
		      				download_session_time: {
		      					min: {
		      						field: "download_session_time"
		      					}
		      				}
		      			}
		      		},
		        	last_10_hits: {
		          		nested: {
		            		path: "es_linked_list"
		          		},
			          	aggs: {
			            	last_10: {
			              		top_hits: {
			                		sort: [
				                  		{
				                    		"es_linked_list.day_id" => {
				                      			order: "desc"
				                    		}	
				                  		}
			                		], 
			                		size: 10,
			                		_source: ["es_linked_list.data_point.close","es_linked_list.data_point.open","es_linked_list.data_point.low","es_linked_list.data_point.high","es_linked_list.data_point.volume","es_linked_list.data_point.day_of_month","es_linked_list.data_point.month_of_year","es_linked_list.data_point.year","es_linked_list.data_point.poller_session_id","es_linked_list.data_point.poller_session_date","es_linked_list.data_point.poller_processor_session_id","es_linked_list.data_point.poller_processor_session_date","es_linked_list.data_point.datapoint_index","es_linked_list.data_point.price_change_verified"
			                		]
			              		}
			            	}
			      		}
		        	}
		      	}
	    	}
		}
	end

	DOWNLOAD_HISTORY_EVENTS = ["A1e-DOWNLOADING_ENTITY","A1i-ENTITY_DOWNLOAD_ERROR","A1h-ENTITY_FORCE_REDOWNLOAD","A1g-ENTITY_EXPECTED_DATAPOINT_ABSENT","A1f-ENTITY_DOWNLOADED_DATE_AND_DATAPOINTS","A1j-ENTITY_NO_NEW_DATAPOINTS","A1d11-ENTITY_FILTERED_RECENT_DOWNLOAD"]
	# the argumen has the download history.
	# what about frontend update ?
	# was it successfull or not.
	# this can be combined.
	# add the frontend update things to it.
	# this is good enough to solve this
	# now display the error better.
	def self.download_history_query(args={})
		{
			bool: {
				must: [
					{
						term: {
							entity_unique_name: args[:entity_unique_name]
						}
					},
					{
						terms: {
							event_name: DOWNLOAD_HISTORY_EVENTS
						}
					}
				]
			}
		}
	end

	def self.download_history_aggregation(args={})
		{
	    	entities: {
	      		terms: {
	        		field: "entity_unique_name",
	        		size: 10,
	        		exclude: ["all_entities"]
	      		},
		      	aggs: {
		      		last_10_poller_sessions: {
		      			terms: {
		      				field: "poller_session_id",
		      				order: {
		      					download_session_time: "desc"
		      				}
		      			},
		      			aggs: {
		      				download_events: {
		      					terms: {
		      						field: "event_name",
		      						include: DOWNLOAD_HISTORY_EVENTS
		      					}
		      				},
		      				download_session_time: {
		      					min: {
		      						field: "download_session_time"
		      					}
		      				}
		      			}
		      		}
		      	}
		    }
		}
	end

	def self.download_history(args={})

		search_response = Elasticsearch::Persistence.client.search :body => {
			size: 0,
			query: download_history_query(args),
			aggs: download_history_aggregation(args)
		}

		#puts "download history search response aggregation is:"
		#puts JSON.pretty_generate(search_response["aggregations"])

		entity_bucket = search_response["aggregations"]["entities"]["buckets"][0]

		poller_sessions = []
		entity_bucket["last_10_poller_sessions"]["buckets"].each do |poller_session|
			puts "poller session is====>"
			puts JSON.pretty_generate(poller_session)
			poller_sessions << {
				:poller_session_id => poller_session["key"],
				:poller_session_date => poller_session["download_session_time"]["value_as_string"],
				:events => poller_session["download_events"]["buckets"].map{|c| c["key"]}
			}
		end

		poller_sessions
	end

	## returns an array of entities, with entity_unique_name and datapoints.
	def self.ticks(args={})
		#puts "the entities query is:"
		#puts JSON.pretty_generate(entities_query(args))
		#puts "-----------------------------------------"

app/views/entities/_correlations_with_indices.html.erb
<h3 class="header light" style="padding-left: 1rem; margin-bottom: 1rem; margin-top:3rem;"><i class="material-icons" data-icon="collections_bookmark"></i><span style="margin-left: 0.5rem;">Tips From Other Stocks</span></h3>
<div class="divider" style="width:65%; margin-left: 1rem; margin-bottom: 0rem;"></div>
<!-- go to an exchange and show combinations -->
<div class="row" style="padding-left: 0.75rem; padding-right: 0.75rem; margin-top: 2.00rem;">
	<ul class="collection">
		<!-- we will have to get exchanges -->
		<!-- or we will fuck up the name -->
		<% @entity.combinations.each do |combination| %>
		    <li class="collection-item">
		      <%= link_to stocks_path({:entity => {:stock_exchange => combination["exchange_name"], :combine_with => @entity.stock_name}}) do %>
		      	<span class="title">Correlations between <%= combination["exchange_name"] %> stocks and <%= @entity.stock_name %></span>
		      <% end %>
		    </li>
		<% end %>
	</ul>
</div>

app/views/entities/_entity_combinations.html.erb
<!-- order transfer -->
<div id="combinations" style="padding-bottom:2rem;">
	<% @entity.combinations.each do |combination| %>

		<div class="row stock_exchange" id="<%= combination['exchange_name'] %>" style="margin-bottom: 0px !important; margin-top: 1.5rem;">
			<div class="col l12 s12 m12">
				<ul class="collection with-header center" style="margin-bottom: 0px !important;">
					<li class="collection-header"><h4>Correlations with <%= combination["exchange_name"] %> Stocks</h4>
					</li>
				</ul>
			</div>
		</div>

		<div class="row" id="<%= combination['exchange_name'] %>_entities" style="display: none; margin-bottom: 0px !important;">
			<div class="col l12 s12 m12">
				<ul class="collection with-header">
					<li class="collection-header center" style="padding: 1rem !important;">
						<% combination["entities"].each do |entity| %>
							<div data-exchange-div-id="<%= combination['exchange_name'] %>" data-entity="<%= JSON.generate(entity) %>" style="margin-bottom: 0px !important; margin-top: 0.5rem; background-color: white; border: 1px solid; border-color: #90a4ae; cursor: pointer;" id="<%= entity['primary_entity_id'] %>" class="chip blue-grey-text entity">
								<%= entity["primary_entity_name"] %>
							</div>
						<% end %>
					</li>
				</ul>
			</div>
		</div>

		<div class="row" id="<%= combination['exchange_name'] %>_entity_combinations" style="display:none;">
			<% combination["entities"].each do |entity| %>
				<div style="display:none;" class="entity_combination" id="entity_combination_<%= entity['primary_entity_id'] %>">
					<div style="margin-bottom: 0px !important; margin-top: 0.5rem; background-color: white; border: 1px solid; border-color: #90a4ae; cursor: pointer;" class="col s10 m10 l10 offset-l1 offset-m1 offset-s1 center chip blue-grey-text">
						<a href="<%= @entity.stock_name %>/with_stock/<%= entity['primary_entity_name'] %>">More Correlations for <%= entity['primary_entity_name'] %> VS <%= @entity.stock_name %></a>
					</div>
				</div>
			<% end %>
		</div>

	<% end %>
</div>

app/views/entities/_information_card.html.erb
  <div class="card col l6 m6 s12">
    <div class="card-content">
      <!-- we have to append here -->
      <span class="card-title blue-grey-text" style="font-weight: 500"><i data-icon="<%= @entity.get_icon %>" class="material-icons"></i><%= @entity.stock_name %></span>
      <p class="green-text"><%= @entity.stock_description %></p>
    </div>
    <div class="card-tabs" style="margin-left: -0.75rem; margin-right: -0.75rem;">
      <ul class="tabs tabs-fixed-width">
        <li class="tab"><a href="#<%= @entity.id.parameterize %>_positive_indicators">Positive</a></li>
        <li class="tab"><a href="#<%= @entity.id.parameterize %>_negative_indicators">Negative</a></li>
      </ul>
    </div>
    <div class="card-content grey lighten-4" style="display:none; margin-left: -0.75rem; margin-right: -0.75rem;">
      <div id="<%= @entity.id.parameterize %>_positive_indicators"><%= render :partial => "/entities/information_card/positive_results" %></div>
      <div id="<%= @entity.id.parameterize %>_negative_indicators"><%= render :partial => "/entities/information_card/negative_results" %></div>
    </div>
  </div>

app/views/entities/_more_button.html.erb
<%= link_to "More", stocks_path(:entity => {:from => @from, :stock_exchange => exchange_name, :stock_is_indicator => @entities.first.stock_is_indicator }), class: "waves-effect waves-light btn-large",  remote: true %>

app/views/entities/_prev_next.html.erb
<div class="row">

	<% if @entity.from.to_i > 0 %>
		<div class="col l6 m6 s6 right-align">
			<%= link_to "Prev", combination_entity_path(:id => @entity.stock_impacted, :primary_stock_id => @entity.stock_primary, :from => (@entity.from.to_i + @entity.stock_top_results.size).to_s), {:class => "waves-effect waves-light btn"} %>
		</div>
		<div class="col l6 m6 s6 left-align">
			<%= link_to "Next", combination_entity_path(:id => @entity.stock_impacted, :primary_stock_id => @entity.stock_primary, :from => (@entity.from.to_i + @entity.stock_top_results.size).to_s), {:class => "waves-effect waves-light btn"} %>
		</div>
	<% else %>
		<div class="col l6 m6 s6 offset-l3 offset-m3 offset-s3 center">
			<%= link_to "Next", combination_entity_path(:id => @entity.stock_impacted, :primary_stock_id => @entity.stock_primary, :from => (@entity.from.to_i + @entity.stock_top_results.size).to_s), {:class => "waves-effect waves-light btn"} %>
		</div>
	<% end %>
</div>

app/views/entities/_related_queries_card.html.erb
<div class="row">
	<div class="col l12 s12 m12">
		<!-- populate this via js erb -->
		<!-- i want with indicators, and also with other entities -->
		<!-- so other entities we will get -->
		<ul class="collection with-header">
			<li class="collection-item blue-grey-text" style="font-weight: 500; font-size: 24px; padding-top: 20px; padding-bottom: 20px;">Related Results</li>
			<% @entity.combinations.each do |combination| %>
				<!-- so this is a combination -->
				<% entity = combination["entities"].sample %>
				
				<li class="collection-item">
					<%= link_to (combination_entity_path(:id => entity["impacted_entity_id"], :primary_stock_id => entity["primary_entity_id"])) do %>
						How do <b><%= entity["primary_entity_name"] %>'s</b> indicators affect <b><%= @entity.stock_name %></b>?
					<% end %>
				</li>
			<% end %>
		</ul>
	</div>
</div>

app/views/entities/_show.html.erb
<div class="row">
	<div class="col s12 m12 l12">
	  <div class="card">
	    <div class="card-image">
	      <img class="entity_background" style="height: 200px">
	    </div>
	    <div class="card-content">
	      <span class="card-title blue-grey-text" style="font-weight: 300; font-size:44px; margin-bottom:1rem;"><%= @entity.page_title %></span>
	      <p style="font-size: 20px;"><%= @entity.page_description %></p>
	    </div>
	    <div class="card-action">
	      <!-- here the title and description will be different -->
	      <%= link_to "Positive Indicators", direction_entity_path(:id => @entity.stock_name.to_s, :trend_direction => "rise") %>
	      <%= link_to "Negative Indicators", direction_entity_path(:id => @entity.stock_name.to_s, :trend_direction => "rise") %>
	    </div>
	  </div>
	</div>
</div>

<!-- would be better to -->

<div class="row" style="margin-bottom: 10px !important; display: none;">
	<div class="col l12 s12 m12">
		<ul class="collection with-header">
			<li class="collection-header"><h4><i class="material-icons" data-icon="storage" style="margin-right:1rem;"></i>Latest Trends</h4></li>
		</ul>
	</div>
</div>


<h3 class="header light" style="padding-left: 1rem; margin-bottom: 1rem; margin-top:3rem;"><i class="material-icons" data-icon="collections_bookmark"></i><span style="margin-left: 0.5rem;">Top Trends</span></h3>
<div class="divider" style="width:30%; margin-left: 1rem; margin-bottom: 1rem;"></div>

<div class="row">
	<% puts "total top results are: #{@entity.stock_top_results.size}" %>
	<% @entity.stock_top_results.each do |result| %>
		<%= render :partial => "/entities/summary_card", locals: {result: result } %>	
	<% end %>
</div>

<%= render :partial => "/entities/paginate" %>


<%= render :partial => "/entities/correlations_with_indices" %>

<% if @entity.is_index? %>
	<%= render :partial => "/exchanges/components" %>
<% end %>

<!-- render :partial => "/entities/entity_combinations" -->

app/views/entities/_show_combination.html.erb
<div class="row">
	<div class="col s12 m12 l12">
	  <div class="card">
	    <div class="card-image">
	      <img class="entity_background" style="height: 200px">
	    </div>
	    <div class="card-content">
	      <span class="card-title blue-grey-text" style="font-weight: 300; font-size:44px; margin-bottom:1rem;"><%= @entity.page_title %></span>
	      <p style="font-size: 20px;"><%= @entity.page_description %></p>
	      <p>Last Updated: <%= @entity.updated_at %></p>
	    </div>
	    <!-- this is not a combination, just finish indicator. -->
	    <div class="card-action">
	      <%= link_to @entity.stock_primary, stock_path(@entity.stock_primary_id) %>
	      <%= link_to @entity.stock_impacted, stock_path(@entity.stock_impacted_id) %>
	    </div>
	  </div>
	</div>
</div>

<!-- would be better to -->

<div class="row" style="margin-bottom: 10px !important;">
	<div class="col l12 s12 m12">
		<ul class="collection with-header">
			<li class="collection-header"><h4><i data-icon="storage" class="material-icons" style="margin-right:1rem;"></i>Latest Correlations</h4></li>
		</ul>
	</div>
</div>

<% @entity.stock_top_results.each_slice(1) do |results| %>
	<div class="row">
		<% results.each do |result| %>
			<%= puts result %>
		    <%= render :partial => "/entities/summary_card", locals: {result: result } %>
		<% end %>
	</div>
<% end %>


<%= render :partial => "/entities/paginate" %>

app/views/entities/_summary_card.html.erb
<div id="<%= result['_id'] %>" class="result col s12 m12 l12 summary_card" data-result="<%= JSON.generate(result) %>">
  <div class="card" style="margin-top:1.5rem;">
      <div class="card-content grey-text text-lighten-1" style="padding-bottom:20px !important;">

          <span class="card-title" style="font-weight:600 !important; font-size:26px !important;">
            <i class="fas fa-industry"></i>
            <%= link_to result_path(result["_id"],{eid: result["_source"]["impacted_entity_id"]}) do %>
              <span class="grey-text text-lighten-1">What happens to</span> <span class="blue-grey-text"><%= result["_source"]["setup"].gsub(/What happens to/,'').html_safe %></span>
            <% end %>
          </span>

          <% if result['_source']['rises_or_falls'] =~ /rise/ %>
              <% text_color = "green-text" %>
              <% icon = "trending_up" %>
          <% else %> 
              <% text_color = "red-text" %>
              <% icon = "trending_down" %>
          <% end %>

          <div class="<%= text_color %>" style="margin-top: 1.5rem;font-size:22px; font-weight: 400; margin-bottom:1rem; !important">
            <i class="material-icons" data-icon="<%= icon %>"></i>Historically, <b><%= result['_source']['target'] %></b><%= result["_source"]["rises_or_falls"] %>  <b><%= result["_source"]["percentage"] %>%</b> of the times. <span><br></span>
          </div>

          <div class="grey-text text-lighten-1" style="margin-top:1.5rem;">
            <span data-chart-id="search_result_chart_<%= result['_id'] %>" class="toggle_search_result_chart">
              <i style="vertical-align: bottom" class="material-icons"data-icon="insert_chart"></i>Chart
            </span>
          </div>

          <div id="search_result_chart_<%= result['_id'] %>_holder" style="display:none;">
              <canvas style="position: relative; margin:auto; height: 50vh; max-height: 50vh;" id="search_result_chart_<%= result['_id'] %>" />
          </div>

      </div>
  </div>
</div>

app/views/entities/index.html.erb
<% first_entity = @entities_by_exchange[@entities_by_exchange.keys[0]][:stocks][0] %>

<% first_exchange = @entities_by_exchange[@entities_by_exchange.keys[0]] %>
<!-- basically on combination concern -->
<!-- give paginate on the other buttons -->
<% unless first_entity.combine_with.blank? %>
	<!-- we are combining and entity with the entites of an exchange -->
	<!-- so we have come till here -->
	<!-- so both tests have the same id -->
	<!-- 5eec11e8acbcd6019bce4e1d5eec137cacbcd628985698fc -->
	<!-- 5eec11e8acbcd6019bce4e1f5eec137cacbcd628985698fd -->
	<div class="row">
		<div class="col s12 m12 l12">
		  <div class="card">
		    <div class="card-image">
		      <img class="entity_background" style="height: 200px">
		    </div>
		    <div class="card-content">
		      <span class="card-title blue-grey-text" style="font-weight: 300; font-size:44px; margin-bottom:1rem;"><%= first_entity.page_title %></span>
		      <p style="font-size: 20px;"><%= first_entity.page_description %></p>
		    </div>
		    <div class="card-action">
		    </div>
		  </div>
		</div>
	</div>

	<div class="row">
		<ul class="collection with-header">
	        <li class="collection-header"><h4>Choose A Combination</h4></li>
	        <% @entities_by_exchange[@entities_by_exchange.keys[0]][:stocks].each do |stock| %>
	        	<%= link_to combination_entity_path(stock.combine_with,stock.stock_name) do %>
	        		<li class="collection-item"><%= (stock.combine_with + " vs " + stock.stock_name) %></li>
	        	<% end %>
	        <% end %>
	    </ul>
	</div>

<% else %>
	<!-- if combine with is true, render that -->
	<!-- we can show a simple list of all the stocks, by exchange name -->
	<% @entities_by_exchange.keys.each do |exchange_name| %>
		<div id="<%= exchange_name.parameterize %>" class="col l12 m12 s12">
			<% @entities = @entities_by_exchange[exchange_name][:stocks] %>
			<% @from = @entities_by_exchange[exchange_name][:next_from] %>
			<!-- if combine with is true, then we show combination -->
			<div id ="<%= exchange_name.parameterize %>_stocks">
				<% @entities.each do |entity| %>
					<% @entity = entity %>
					<%= render :partial => "/entities/show_summary" %>
				<% end %>
			</div>
			<div id="more_button_holder" class="center">
				<%= render :partial => "/entities/more_button", locals: { exchange_name: exchange_name } %>
			</div>
		</div>
	<% end %>


<% end %>